source 'https://rubygems.org'
gem 'cucumber', '1.3.19'
gem 'capybara', '2.4.4'
gem 'byebug'
gem 'rspec-expectations'
gem 'poltergeist', ">= 1.4.0"
gem 'selenium-webdriver', '2.46.2'
gem 'curb'
gem 'parallel_tests'
gem 'capybara-screenshot'
gem 'sauce', '3.5.11'
gem 'sauce-cucumber'
gem 'sauce-connect'
gem 'rake'